### ISSUE TITLE
About the Max Sequence Length

### ISSUE THREAD

**Issue by xu3kev** [deepseek-ai/DeepSeek-Coder#10]
Hi,

Some of the released models have [config](https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base/blob/9f75359417c2ccb41d8e18806de2f7b1d85e4390/config.json#L11) 'max_position_embeddings' set to 8192 instead of 16384. However, in the repo readme, the models are said to have a 16k context size. Could you clarify what the max sequence length of these models is? Thanks!

**Comment by pkuzqh** [comment]
Sorry for the mistake. We have fixed it.

**Comment by xu3kev** [comment]
Thank you!
