### ISSUE TITLE
Repository Level Code Completion format question

### ISSUE THREAD

**Issue by zch-cc** [deepseek-ai/DeepSeek-Coder#116]
Hi, first of all, thanks for getting this model and make it open source. 
I have a quick question on the format of Repository Level Code Completion, from the readme, it is # filename + code. I wonder # character is the format for Repository level or # make it as the comment for python.
Take an example, if the code language is cpp, should we use // instead to make it as a comment or still use # ? 
thanks for answering my questions.

**Comment by luofuli** [comment]
For cpp, we use# filename + code. @zch-cc

**Comment by icnahom** [comment]
Why not use something consistent, like `<filename>` from starcoder?
