### ISSUE TITLE
eos_token_id for v1.5 model

### ISSUE THREAD

**Issue by G07cha** [deepseek-ai/DeepSeek-Coder#118]
A rookie question, I was following README's guide on [setting up deepseek-coder-instruct to complete the code](https://github.com/deepseek-ai/DeepSeek-Coder?tab=readme-ov-file#how-to-use-the-deepseek-coder-instruct-to-complete-the-code) and wanted to try it with [deepseek-coder-7b-instruct-v1.5](https://huggingface.co/deepseek-ai/deepseek-coder-7b-instruct-v1.5), but there `eos_token_id` is set to `100015` unlike `32021` for regular `deepseek-coder-7b-instruct` model. Can `eos_token_id: 32014` still used for v1.5 model?

**Comment by guoday** [comment]
The eos_token_id of deepseek-coder-7b-instruct v1.5 is 100015, because the vocabulary is different from v1.

**Comment by G07cha** [comment]
@guoday do you know what value `eos_token_id` of v1.5 model should be set to when support for code completion is needed?

**Comment by guoday** [comment]
Are you referring to deepseek-coder-base-v1.5? The `eos_token_id` is 100001. However, when you use the coder for code completion, you shouldn't be able to stop generation using the `eos_token_id`. Typically, in code completion, you need to specify when to stop generation yourself, such as generating one line, generating a block, or generating 64 tokens.

**Comment by G07cha** [comment]
Ah clear, couldn't make the connection between `eos_token_id` from base model and instruct one, thanks!
