### ISSUE TITLE
How many tokens of code in pretraining

### ISSUE THREAD

**Issue by bigeagle** [deepseek-ai/DeepSeek-Coder#121]
Hi there,

According to the README, DeepSeek-Coder is trained on 2T tokens, where 87% is code. So there should be around 1.74T tokens of code in the pretrain data. However, the tech-report says _the training data for code has a data volume of 798 GB_. 

Let's say, on average, 4-bytes = 1 token, then the code data contains only 200G tokens, which is far from the total 2T tokens for the pretraining.

I'm not sure which part is wrong. Can you explain?

Yours,
Justin

**Comment by guoday** [comment]
about 350B code tokens. These tokens will be trained by 4～5 epochs

**Comment by bigeagle** [comment]
Thanks!
