### ISSUE TITLE
为啥运行完测试demo，感觉显卡资源不释放，必须重启服务器才可以？

### ISSUE THREAD

**Issue by lsy1990** [deepseek-ai/DeepSeek-Coder#13]
![Image_20231106083044](https://github.com/deepseek-ai/DeepSeek-Coder/assets/5174292/ce697f0a-36cc-49c6-803a-9919a271e8da)

**Comment by guoday** [comment]
我在本地上测试没有问题，你看看进程是不是没有杀死，所以一直没释放显存
