### ISSUE TITLE
Pretraining code

### ISSUE THREAD

**Issue by Calvinnncy97** [deepseek-ai/DeepSeek-Coder#132]
May I know if the pretraining code will be released? Besides, what is the data format for the pretraining? Would love to know these as it will be very helpful in continued pretraining of the model.

Thank you. 

Best regards

**Comment by guoday** [comment]
Hello, there are currently no plans to open-source the pre-training code. The format for pre-training is consistent with most of the methods currently in use, where different samples are concatenated together and separated by a special token.

**Comment by Calvinnncy97** [comment]
Got it. Thank you.
