### ISSUE TITLE
Trying to finetune DeepSeek-Coder on custom Dataset

### ISSUE THREAD

**Issue by A-Janj** [deepseek-ai/DeepSeek-Coder#137]
![image](https://github.com/deepseek-ai/DeepSeek-Coder/assets/72404946/2ddc5d9b-c00b-4f04-97e5-d491b1bf0c0b)

I am trying to finetune DeepSeek-Coder but I am getting this -9 kill code, and I have no idea why. My dataset is in the following format:
[{"instruction": "", "output": ""}, {"instruction": "", "output": ""}]

The following is the error I am getting when running the [finetune_deepseekcoder.py](https://github.com/deepseek-ai/DeepSeek-Coder/blob/main/finetune/finetune_deepseekcoder.py) code.

**Comment by DejianYang** [comment]
> I am trying to finetune DeepSeek-Coder but I am getting this -9 kill code, and I have no idea why. My dataset is in the following format:

Please check if you have enough CPU memory?

**Comment by A-Janj** [comment]
> > I am trying to finetune DeepSeek-Coder but I am getting this -9 kill code, and I have no idea why. My dataset is in the following format:
> 
> Please check if you have enough CPU memory?

I have 64 GB RAM (CPU memory). How much does deepseek require to get finetuned?

**Comment by DejianYang** [comment]
> > > I am trying to finetune DeepSeek-Coder but I am getting this -9 kill code, and I have no idea why. My dataset is in the following format:
> > 
> > 
> > Please check if you have enough CPU memory?
> 
> I have 64 GB RAM (CPU memory). How much does deepseek require to get finetuned?

I do not have exact number of RAM required by finetune. The DeepSpeed is used in the finetune script which requires a lot of RAM to do cpu offload. You can try another config of deepspeed to reduce the cpu memory used if you have enough GPU memory.

**Comment by A-Janj** [comment]
> > > > I am trying to finetune DeepSeek-Coder but I am getting this -9 kill code, and I have no idea why. My dataset is in the following format:
> > > 
> > > 
> > > Please check if you have enough CPU memory?
> > 
> > 
> > I have 64 GB RAM (CPU memory). How much does deepseek require to get finetuned?
> 
> I do not have exact number of RAM required by finetune. The DeepSpeed is used in the finetune script which requires a lot of RAM to do cpu offload. You can try another config of deepspeed to reduce the cpu memory used if you have enough GPU memory. Maybe you can try our 1b model first.

Can you give me an idea of how much GPU VRAM I would require if I have 64 GB system RAM?
Moreover should I put false instead of true in offload cpu parameters in ds_config_zero3.json, like:
 "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": false
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": false
        },

**Comment by A-Janj** [comment]
![Screenshot from 2024-03-13 12-54-34](https://github.com/deepseek-ai/DeepSeek-Coder/assets/72404946/ce454486-6c2f-4c61-9c28-0a9e69d5b03f)

I was able to finetune the **6.7b parameter** model using **1 x H100 80GB SXM5 (80 GB VRAM and 251 GB RAM  24 vCPU)**. The Finetune script created files in the given output folder, but **model.safetensors file is only 539.6 kB**.

 Doing inference on the finetuned directory first gave the following **error**:

> "RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
>         size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([32256, 2048]).
>         You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method."

 After setting **ignore_mismatched_sizes=True** argument in the **from_pretrained** method the model is giving gibberish. You can see the inference code and the output in the screenshot.

**Am I missing something?**

**Comment by DejianYang** [comment]
> size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([32256, 2048]).

https://huggingface.co/docs/accelerate/usage_guides/deepspeed#saving-and-loading

**Comment by seancarmod-y** [comment]
@DejianYang I'm looking to fine-tune deepseek-coder-1.3b-base. Ideally, I'd like to do it using huggingface libraries as I have done for tinyllama in the attached file. Is this possible or do I need to use the finetune_deepseekcoder.py (can this even be used for the 1.3b model?)
[fine_tune_tiny_llama.txt](https://github.com/deepseek-ai/DeepSeek-Coder/files/14591592/fine_tune_tiny_llama.txt)

**Comment by DejianYang** [comment]
> fine_tune_tiny_llama.txt
Yes, you can use the script to finetune our model just like you are using other llama models.

**Comment by A-Janj** [comment]
> > size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([32256, 2048]).
> 
> https://huggingface.co/docs/accelerate/usage_guides/deepspeed#saving-and-loading

Thank you so much for your time and help. This helped me in understanding the different deepspeed config files and ZeRO stages.
What I did to resolve my issue was to put trainer.save_model() and tokenizer in the finetune script, done as below:

```
trainer.train()
trainer.save_model("SaveOutputFolder")
trainer.tokenizer.save_pretrained("SaveOutputFolder")
trainer.save_state()
```
Thanks once again so much for all your help.

**Comment by seancarmod-y** [comment]
> > fine_tune_tiny_llama.txt
> > Yes, you can use the script to finetune our model just like you are using other llama models.

Hi, that's great, thanks. I can't seem to find documentation on how to format the custom dataset. For both Llama2 and Tinyllama I have formatted it as a csv where there is a 'text' column. The formats of each row are:
Llama2: <s>[INST] prompt  [/INST] Llama2 answer <\s>
Tinyllama: <|user|>
prompt
<|assistant|>
Tinyllama answer
I then load the dataset like this:
from datasets import load_dataset
dataset = load_dataset(dataset_folder, split="train")

Is there a similar format that I can follow for deepseek-coder-1.3b?

**Comment by LarkLeeOnePiece** [comment]
@A-Janj  How did you solve your problem? I met this problem too.

**Comment by LarkLeeOnePiece** [comment]
Sorry, can you solve the mismatched_sizes problem after adding"trainer.train()
trainer.save_model("SaveOutputFolder")
trainer.Tokenizer.save_pretrained("SaveOutputFolder")
trainer.save_state()"
I met the same prblem, could you help me out?
Do you use the AutoTokenizer.from_pretrained and AutoModelForCausalLM.from_pretrained to load the model and tokenier?
