### ISSUE TITLE
这里微调脚本有什么特别处理吗？能给一下这里微调的的脚本细节吗？

### ISSUE THREAD

**Issue by wyrcode** [deepseek-ai/DeepSeek-Coder#14]

**Comment by guoday** [comment]
微调脚本没什么特别的处理，与大部分微调都一样，只算response的loss

**Comment by JianqiaoLu** [comment]
你们是用的fastchat微调的嘛，好像跑起来之后lr一直是0，虽然我用了xformer，（不过我猜不是这个原因？

**Comment by zhangxjohn** [comment]
我finetune的时候lr也是0, loss 不下降，没有用xformer，同求solution

**Comment by JianqiaoLu** [comment]
> 我finetune的时候lr也是0, loss 不下降，没有用xformer，同求solution

有个离谱的事情，我发现你多跑几个epoch有机会出现lr...虽然也不正常。但是至少有了非0的lr. ;)

**Comment by zhangxjohn** [comment]
> > 我finetune的时候lr也是0, loss 不下降，没有用xformer，同求solution
> 
> 有个离谱的事情，我发现你多跑几个epoch有机会出现lr...虽然也不正常。但是至少有了非0的lr. ;)

是非常小趋于0且不变化是吗？依然不会收敛？

**Comment by wyrcode** [comment]
> 你们是用的fastchat微调的嘛，好像跑起来之后lr一直是0，虽然我用了xformer，（不过我猜不是这个原因？

我微调lr和loss是正常的。也是用的和fs差不多的脚本

**Comment by JianqiaoLu** [comment]
> > > 我finetune的时候lr也是0, loss 不下降，没有用xformer，同求solution
> > 
> > 
> > 有个离谱的事情，我发现你多跑几个epoch有机会出现lr...虽然也不正常。但是至少有了非0的lr. ;)
> 
> 是非常小趋于0且不变化是吗？依然不会收敛？



> > 你们是用的fastchat微调的嘛，好像跑起来之后lr一直是0，虽然我用了xformer，（不过我猜不是这个原因？
> 
> 我微调lr和loss是正常的。也是用的和fs差不多的脚本

心态崩了，为啥我train vicunav1.5正常，但是训练llama2就g了
