### ISSUE TITLE
Are NTP and FIM 2 separate stages of training, or are they combined?

### ISSUE THREAD

**Issue by Calvinnncy97** [deepseek-ai/DeepSeek-Coder#146]
After reading through the issues, I understand that repo level concatenation is done for NTP. My question is are these 2 separate stages of training or are they combined?

Thank you.

**Comment by pkuzqh** [comment]
Combined.

**Comment by Calvinnncy97** [comment]
If that's the case, does FIM segmentation also happen to repo concatenated documents?

**Comment by pkuzqh** [comment]
Yes.

**Comment by Calvinnncy97** [comment]
Thank you!
