### ISSUE TITLE
使用单A100加载33b模型，推理很慢，请问有模型并行的方案吗？

### ISSUE THREAD

**Issue by MarsMeng1994** [deepseek-ai/DeepSeek-Coder#15]
请问如何做模型并行？

**Comment by guoday** [comment]
A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF

**Comment by MarsMeng1994** [comment]
> A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF

A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？

**Comment by GeeeekExplorer** [comment]
> > A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF
> 
> A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？

我尝试了[tensor_parallel](https://github.com/BlackSamorez/tensor_parallel)是可以的，在模型加载到主存后：
```python
import tensor_parallel as tp
model = tp.tensor_parallel(model, ["cuda:0", "cuda:1"])
```
但是GPT推理主要受限于访存而非计算，我这边跑下来不TP更快。

**Comment by MarsMeng1994** [comment]
> > > A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF
> > 
> > 
> > A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？
> 
> 我尝试了[tensor_parallel](https://github.com/BlackSamorez/tensor_parallel)是可以的，在模型加载到主存后：
> 
> ```python
> import tensor_parallel as tp
> model = tp.tensor_parallel(model, ["cuda:0", "cuda:1"])
> ```
> 
> 但是GPT推理主要受限于访存而非计算，我这边跑下来不TP更快。

感谢，我去试试。就是感觉官方提供的体验版本回复速度很快，但本地部署后没有它那么快，感觉很奇怪，理论上显卡都是A100的话，应该不会差很多。
个人感觉是不是模型前向做了一些并行，比如qkv并行计算。

**Comment by guoday** [comment]
我们部署的时候使用的是VLLM，这个会快很多，如果是直接用hf原来load的话，会比较慢

**Comment by soloice** [comment]
> > > A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF
> > 
> > 
> > A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？
> 
> 我尝试了[tensor_parallel](https://github.com/BlackSamorez/tensor_parallel)是可以的，在模型加载到主存后：
> 
> ```python
> import tensor_parallel as tp
> model = tp.tensor_parallel(model, ["cuda:0", "cuda:1"])
> ```
> 
> 但是GPT推理主要受限于访存而非计算，我这边跑下来不TP更快。

不应当，理论上 TP 会更快的。GPT 推理主要受限于访存是事实，但 TP 可以减轻访存压力，每张卡只访问一部分模型参数。

**Comment by soloice** [comment]
> > > > A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF
> > > 
> > > 
> > > A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？
> > 
> > 
> > 我尝试了[tensor_parallel](https://github.com/BlackSamorez/tensor_parallel)是可以的，在模型加载到主存后：
> > ```python
> > import tensor_parallel as tp
> > model = tp.tensor_parallel(model, ["cuda:0", "cuda:1"])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是GPT推理主要受限于访存而非计算，我这边跑下来不TP更快。
> 
> 感谢，我去试试。就是感觉官方提供的体验版本回复速度很快，但本地部署后没有它那么快，感觉很奇怪，理论上显卡都是A100的话，应该不会差很多。 个人感觉是不是模型前向做了一些并行，比如qkv并行计算。

我们部署用的是 vllm + tp。tp 肯定会让他速度变快的。

**Comment by soloice** [comment]
> > > > A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF
> > > 
> > > 
> > > A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？
> > 
> > 
> > 我尝试了[tensor_parallel](https://github.com/BlackSamorez/tensor_parallel)是可以的，在模型加载到主存后：
> > ```python
> > import tensor_parallel as tp
> > model = tp.tensor_parallel(model, ["cuda:0", "cuda:1"])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是GPT推理主要受限于访存而非计算，我这边跑下来不TP更快。
> 
> 感谢，我去试试。就是感觉官方提供的体验版本回复速度很快，但本地部署后没有它那么快，感觉很奇怪，理论上显卡都是A100的话，应该不会差很多。 个人感觉是不是模型前向做了一些并行，比如qkv并行计算。

补充一下，我们是用 vllm 部署 hai_llm（内部训练框架）的模型，而不是 hf 格式的模型。我们会把  qkv 三次矩阵乘法融合成一次大矩阵乘法，这些在 hf 的 LlamaForCausalLM 里没有做。

**Comment by White-Friday** [comment]
@guoday 你好，我也是用vllm加速，但是启动之后，模型回答的结果会一直不停的回答重复的东西，想知道模型的prompt format或者是eos 终止操作这些，谢谢

**Comment by guoday** [comment]
https://github.com/deepseek-ai/DeepSeek-Coder#4-repository-level-code-completion
prompt format和eos都在这

**Comment by MarsMeng1994** [comment]
> > > > A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF
> > > 
> > > 
> > > A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？
> > 
> > 
> > 我尝试了[tensor_parallel](https://github.com/BlackSamorez/tensor_parallel)是可以的，在模型加载到主存后：
> > ```python
> > import tensor_parallel as tp
> > model = tp.tensor_parallel(model, ["cuda:0", "cuda:1"])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是GPT推理主要受限于访存而非计算，我这边跑下来不TP更快。
> 
> 不应当，理论上 TP 会更快的。GPT 推理主要受限于访存是事实，但 TP 可以减轻访存压力，每张卡只访问一部分模型参数。

会不会是因为decoder是自回归的

**Comment by soloice** [comment]
> > > > > A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF
> > > > 
> > > > 
> > > > A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？
> > > 
> > > 
> > > 我尝试了[tensor_parallel](https://github.com/BlackSamorez/tensor_parallel)是可以的，在模型加载到主存后：
> > > ```python
> > > import tensor_parallel as tp
> > > model = tp.tensor_parallel(model, ["cuda:0", "cuda:1"])
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 但是GPT推理主要受限于访存而非计算，我这边跑下来不TP更快。
> > 
> > 不应当，理论上 TP 会更快的。GPT 推理主要受限于访存是事实，但 TP 可以减轻访存压力，每张卡只访问一部分模型参数。
> 
> 会不会是因为decoder是自回归的

即便自回归模型每次只预测一个词，TP 也可以加速。因为每一层的参数都被切分成了好几块扔到不同的GPU上。我没用过 tensor_parallel 这个库不清楚性能如何，但 TP 确实是可以加速的。

**Comment by GeeeekExplorer** [comment]
> > > > > > A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF
> > > > > 
> > > > > 
> > > > > A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？
> > > > 
> > > > 
> > > > 我尝试了[tensor_parallel](https://github.com/BlackSamorez/tensor_parallel)是可以的，在模型加载到主存后：
> > > > ```python
> > > > import tensor_parallel as tp
> > > > model = tp.tensor_parallel(model, ["cuda:0", "cuda:1"])
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 但是GPT推理主要受限于访存而非计算，我这边跑下来不TP更快。
> > > 
> > > 
> > > 不应当，理论上 TP 会更快的。GPT 推理主要受限于访存是事实，但 TP 可以减轻访存压力，每张卡只访问一部分模型参数。
> > 
> > 
> > 会不会是因为decoder是自回归的
> 
> 即便自回归模型每次只预测一个词，TP 也可以加速。因为每一层的参数都被切分成了好几块扔到不同的GPU上。我没用过 tensor_parallel 这个库不清楚性能如何，但 TP 确实是可以加速的。

我之前分析的不对，理论上的确TP参数更小访存更快，但单卡到多卡引入通信同步了。在A100和H800上测试7B模型的hf代码单卡更快，没有深究tensor_parallel库的实现，乍看维度切分是合理的，也许其他推理框架的两卡TP会比单卡快。

**Comment by MarsMeng1994** [comment]
> > > > > > > A100-80G才能加载33b模型，如果不是80G的话，可以考虑使用GGUF
> > > > > > 
> > > > > > 
> > > > > > A100-80g可以加载，但是模型前向感觉太慢了。除了8bit，4bit量化，有什么并行方案吗？
> > > > > 
> > > > > 
> > > > > 我尝试了[tensor_parallel](https://github.com/BlackSamorez/tensor_parallel)是可以的，在模型加载到主存后：
> > > > > ```python
> > > > > import tensor_parallel as tp
> > > > > model = tp.tensor_parallel(model, ["cuda:0", "cuda:1"])
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 但是GPT推理主要受限于访存而非计算，我这边跑下来不TP更快。
> > > > 
> > > > 
> > > > 不应当，理论上 TP 会更快的。GPT 推理主要受限于访存是事实，但 TP 可以减轻访存压力，每张卡只访问一部分模型参数。
> > > 
> > > 
> > > 会不会是因为decoder是自回归的
> > 
> > 
> > 即便自回归模型每次只预测一个词，TP 也可以加速。因为每一层的参数都被切分成了好几块扔到不同的GPU上。我没用过 tensor_parallel 这个库不清楚性能如何，但 TP 确实是可以加速的。
> 
> 我之前分析的不对，理论上的确TP参数更小访存更快，但单卡到多卡引入通信同步了。在A100和H800上测试7B模型的hf代码单卡更快，没有深究tensor_parallel库的实现，乍看维度切分是合理的，也许其他推理框架的两卡TP会比单卡快。

如果只是对整体模型做tp感觉只会增加通信延迟，但是如果深入到模型内部效果加速应该会体现出来吧
![image](https://github.com/deepseek-ai/DeepSeek-Coder/assets/24523981/0844774d-5e96-4cc2-9f12-1abffb95762c)

**Comment by bohea** [comment]
> 我们部署的时候使用的是VLLM，这个会快很多，如果是直接用hf原来load的话，会比较慢

在vllm中使用了TP吗，tp设置为多少

**Comment by soloice** [comment]
> > 我们部署的时候使用的是VLLM，这个会快很多，如果是直接用hf原来load的话，会比较慢
> 
> 在vllm中使用了TP吗，tp设置为多少

Typically we use TP4 or  TP8

**Comment by Luowaterbi** [comment]
> 我们部署的时候使用的是VLLM，这个会快很多，如果是直接用hf原来load的话，会比较慢
你好，我使用vllm0.2.1post1（A800-80GB）似乎并不支持deepseek，在vllm的[supprt models](https://docs.vllm.ai/en/latest/models/supported_models.html)也没有找到deepseek。我直接运行会报`RuntimeError: vLLM cannot currently support max_model_len=65536 with block_size=16 on GPU with compute capability (8, 0) (required shared memory 264252.0 > available shared memory 166912). This will be fixed in a future release.`的错误。请问你们是自己实现的加速逻辑吗？
