### ISSUE TITLE
使用Ollama运行6.7B，Chat回复空白

### ISSUE THREAD

**Issue by tjlcast** [deepseek-ai/DeepSeek-Coder#23]
你好，

我使用ollama(0.1.7)加载[guff文件](https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF/blob/main/deepseek-coder-6.7b-instruct.Q4_K_M.gguf)

使用的Modelfile为：
```
FROM ./deepseek-coder-6.7b-instruct.Q4_K_M.gguf
PARAMETER temperature 0.7

TEMPLATE """{{ .System }}
### Instruction:
{{ .Prompt }}
### Response:
"""

SYSTEM """You are an advanced AI programming assistant."""
```

加载后运行:
```
ollama run deepseekQ4KM   
>>> hi
    













^C
```
似乎一直在输出“回车”？

**Comment by guoday** [comment]
https://ollama.ai/library/deepseek-coder
你可以看下这个

**Comment by Kouuh** [comment]
> 你好，
> 
> 我使用ollama(0.1.7)加载[guff文件](https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF/blob/main/deepseek-coder-6.7b-instruct.Q4_K_M.gguf)
> 
> 使用的Modelfile为：
> 
> ```
> FROM ./deepseek-coder-6.7b-instruct.Q4_K_M.gguf
> PARAMETER temperature 0.7
> 
> TEMPLATE """{{ .System }}
> ### Instruction:
> {{ .Prompt }}
> ### Response:
> """
> 
> SYSTEM """You are an advanced AI programming assistant."""
> ```
> 
> 加载后运行:
> 
> ```
> ollama run deepseekQ4KM   
> >>> hi
>     
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ^C
> ```
> 
> 似乎一直在输出“回车”？

老哥你解决了吗？咋解决的呀？
