### ISSUE TITLE
Cannot reproduce the results of HumanEval-Python

### ISSUE THREAD

**Issue by Cheungki** [deepseek-ai/DeepSeek-Coder#26]
Thanks for your great work! I'm using the scripts in your repo to evaluate the released DeepSeek-Coder 1.3B (both base version and instruct version) with 8 V100s (therefore I use fp16 as the mixed precision).

But there is a performance gap between my results and those reported in this repo (3% for the base version and around 20% for the instruct version).

I'm wondering how to reproduce the reported results and might this is caused by fp16?

**Comment by pkuzqh** [comment]
The difference of the base model may be caused by the precision and the devices (we evaluate the models on A100s). The difference between the instruct version is caused by the post-processing. We will upload the evaluation scripts of the instruction models soon.
