### ISSUE TITLE
加载33b模型异常

### ISSUE THREAD

**Issue by xiaokai01** [deepseek-ai/DeepSeek-Coder#29]
下载33b 的模型之后，加载不了 ，同样的命令6.7， 1.3的都可以
![image](https://github.com/deepseek-ai/DeepSeek-Coder/assets/40970203/93129845-fc5d-43fd-a5bb-adb67d975fc4)

**Comment by DejianYang** [comment]
Please try to upgrade your `transformers` version to `4.35.0` and try again.
