### ISSUE TITLE
Discussion about possible contamination?

### ISSUE THREAD

**Issue by zkx06111** [deepseek-ai/DeepSeek-Coder#3]
Hi, I appreciate your great contribution to the open-source community!

I wonder if there's any measure you took to prevent contamination in your training corpus or any discussion about it in your technical report.

Thanks

**Comment by guoday** [comment]
What's meaning of contamination? Do you mean low-quality code?

**Comment by jeff31415** [comment]
> What's meaning of contamination? Do you mean low-quality code?

I think he/she means the potential leak of eval sets(eg Human Eval) into pretaining corpus, and the effectiveness of benchmark, sience achievening 79% pass@1 on HumanEval is not common before.🤔

**Comment by guoday** [comment]
I see. We use the same method as https://github.com/bigcode-project/bigcode-dataset/tree/main/decontamination.
As we said [here](https://github.com/deepseek-ai/deepseek-coder#3-procedure-of-data-creation-and-model-training), we apply the same filtering rules as [StarcoderData](https://github.com/bigcode-project/bigcode-dataset) to filter data

**Comment by zkx06111** [comment]
Thanks for the clarification!
