### ISSUE TITLE
Instruction dataset?

### ISSUE THREAD

**Issue by cdj0311** [deepseek-ai/DeepSeek-Coder#33]
Hi, 
   The humaneval of deepseek-7b-instruct is 78.6%, but I can't get the result, which datasets are you training?

**Comment by guoday** [comment]
For open-source datasets, you can try using wizardcoder datasets. We have tried it and it can achieve 78% accuracy.

**Comment by II-Matto** [comment]
@guoday What are the "wizardcoder datasets" exactly and are they publicly available? The authors do not seem to have released the data. It would be so kind of you to provide a link to the mentioned data. Many thanks.

**Comment by guoday** [comment]
https://huggingface.co/datasets/theblackcat102/evol-codealpaca-v1

**Comment by II-Matto** [comment]
Thanks. I will perform some decontamination and try it for fine-tuning.
