### ISSUE TITLE
For evaluating on the MBPP dataset, any code for the instruction-based model?

### ISSUE THREAD

**Issue by wujwyi** [deepseek-ai/DeepSeek-Coder#41]
There are different codes for base model and instruction-based model when evaluated on HumanEval dataset. But I didn't find the code for instruction-based model evaluated on MBPP dataset.

**Comment by DejianYang** [comment]
please refer to https://github.com/deepseek-ai/DeepSeek-Coder/blob/main/Evaluation/MBPP/eval_instruct.py
