### ISSUE TITLE
TensorRT-LLM Support

### ISSUE THREAD

**Issue by anxietymonger** [deepseek-ai/DeepSeek-Coder#44]
We tried to deploy 6.7B instruct model with TensorRT-LLM and Triton Inference Server. The model seems not giving correct generation but only repeating certain characters all the time.

Any instructions about TensorRT-LLM deployment or plans in the future? Thank you.

**Comment by guoday** [comment]
Sorry, we haven't yet studied TensorRT-LLM and Triton Inference Server, so we can't provide help now.

**Comment by johnjyang** [comment]
Hi @anxietymonger, could you share your build script by any chance? I'm trying the following (I took my codellama build script and changed the `rotary_scaling` and `rotary_base`), but the engine is just outputting nonsense. Thank you so much!

```
python build.py \
  --model_dir deepseek-coder-33b-instruct/ \
  --dtype float16 \
  --remove_input_padding \
  --use_gpt_attention_plugin float16 \
  --use_gemm_plugin float16 \
  --use_rmsnorm_plugin float16 \
  --enable_context_fmha \
  --use_parallel_embedding \
  --rotary_base 100000 \
  --rotary_scaling linear 4.0 \
  --vocab_size 32256 \
  --parallel_build \
  --paged_kv_cache \
  --use_inflight_batching \
  --output_dir ./tmp/deepseek-coder/33b-instruct/trt_engines/fp16/4-gpu/ \
  --world_size 4 \
  --tp_size 4 \
  --pp_size 1 \
  --max_input_len 8192 \
  --max_output_len 8192 \
  --max_batch_size 64
```

**Comment by anxietymonger** [comment]
@johnjyang I just used the build script provided in TensorRT-LLM v0.5.0 release, nothing customized.

**Comment by johnjyang** [comment]
@anxietymonger Thanks! Which script exactly? And did you have to convert the model weights to any specific format before the build?
