### ISSUE TITLE
代码输出和官网输出不

### ISSUE THREAD

**Issue by xiaokai01** [deepseek-ai/DeepSeek-Coder#47]
当使用本地代码跑的时候，大于670长度的话，模型直接输出原来的问句是什么意思？为什么同样的句子，代码出不来结果，官网可以.
![image](https://github.com/deepseek-ai/DeepSeek-Coder/assets/40970203/685d23de-d712-4190-94bd-bfc97a8a391c)
![image](https://github.com/deepseek-ai/DeepSeek-Coder/assets/40970203/767da29c-4639-485e-bb69-17f58836fef5)

**Comment by guoday** [comment]
你可能需要确保使用对的prompt
https://github.com/deepseek-ai/DeepSeek-Coder#3-chat-model-inference
