### ISSUE TITLE
显存占用过高，发现示例是fp32

### ISSUE THREAD

**Issue by GeeeekExplorer** [deepseek-ai/DeepSeek-Coder#51]
运行 README 里的例子，发现尽管[config](https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-instruct/blob/main/config.json)里有`torch_dtype`，但`transformers`加载仍然是float32，建议在 README 示例中`from_pretrained`指定`torch_dtype="auto"`，这样是bfloat16。

P.S. SM低于80的用户应该不能使用bfloat16。

```python
path = "./DeepSeek"
tokenizer = AutoTokenizer.from_pretrained(path)
model = AutoModelForCausalLM.from_pretrained(path, torch_dtype="auto").cuda()
total = 0
for param in model.parameters():
    total += param.numel() * param.element_size()
print(total / 2**30, "GB")
print(next(model.parameters()).dtype)
```

**Comment by soloice** [comment]
Thanks for pointing this out! Already fixed.
