### ISSUE TITLE
DeepSeek Chat

### ISSUE THREAD

**Issue by SinanAkkoyun** [deepseek-ai/DeepSeek-Coder#61]
Hi! Do you plan on releasing the DeepSeek Chat models?

**Comment by darkworks** [comment]
what is DeepSeek Chat ?

**Comment by SinanAkkoyun** [comment]
![image](https://github.com/deepseek-ai/DeepSeek-Coder/assets/43215895/d2f54603-6423-448d-8c5c-6749a895d222)

**Comment by SinanAkkoyun** [comment]
Actually they just released the LLM version! Thank you so much DeepSeek ❤️
