### ISSUE TITLE
示例3代码运行报错

### ISSUE THREAD

**Issue by Halflifefa** [deepseek-ai/DeepSeek-Coder#8]
>>> from transformers import AutoTokenizer, AutoModelForCausalLM
>>> tokenizer = AutoTokenizer.from_pretrained("./deepseek-coder-1.3b-instruct", trust_remote_code=True)
>>> model = AutoModelForCausalLM.from_pretrained("./deepseek-coder-1.3b-instruct", trust_remote_code=True).cuda()
>>> messages=[
...     { 'role': 'user', 'content': "write a quick sort algorithm in python."}
... ]
>>> inputs = tokenizer.apply_chat_template(messages, return_tensors="pt").to(model.device)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'LlamaTokenizerFast' object has no attribute 'apply_chat_template'

**Comment by DejianYang** [comment]
please upgrade your transformers to latest version and try again.

**Comment by soloice** [comment]
Added [https://github.com/deepseek-ai/DeepSeek-Coder/blob/main/requirements.txt](https://github.com/deepseek-ai/DeepSeek-Coder/blob/main/requirements.txt)
