### ISSUE TITLE
Evaluation on PAL-Math just read the completion files in rank 0.

### ISSUE THREAD

**Issue by MingfengXue** [deepseek-ai/DeepSeek-Coder#86]
In lines 164-168 of the file Evaluation/PAL-Math/run.py, in the for loop, the file path is "rank_{args.rank}.json" but not rank_{rank}.json, thus only the generated results from the rank_0 file are added to the samples, which will result in only a small fraction of the samples being evaluated.

code here:
```
for rank in range(args.world_size):
    out_file = f"outputs/{args.model_name}/{args.data_name}/world_size_{args.world_size}_rank_{args.rank}.json"
    if not os.path.exists(out_file):
        raise FileNotFoundError(f"File {out_file} does not exist.")
    samples.extend(json.load(open(out_file,"r")))
```

**Comment by guoday** [comment]
Thanks. You are right and we will fix the numbers. Thanks
