### ISSUE TITLE
Impact of repo-level code concat

### ISSUE THREAD

**Issue by feiyuvl** [deepseek-ai/DeepSeek-Coder#9]
Very impressive work. Does the repo-level code conact improve humaneval result?

**Comment by guoday** [comment]
In our experiment, repo-level code would slightly hurt performance of benchmark. However, it will enhance long context modeling and repo-level completion.

**Comment by feiyuvl** [comment]
@guoday Thanx for your reply. Another question, how many epochs do you train on the 2T tokens dataset?

**Comment by guoday** [comment]
4-5 epochs

**Comment by feiyuvl** [comment]
So the total training tokens  is about 10T? Amazing

**Comment by guoday** [comment]
No. The total data is about 400-500B. We train the model for 4-5 epochs, resulting 2T.

**Comment by feiyuvl** [comment]
This amount is equal to the starcoder dataset. Do you possibly resuse the stack dataset, and apply a more advanced data filter alogrithm, or  do you download more code data than stack, and implment more stricted data cleaning algorithms?

**Comment by feiyuvl** [comment]
Deepseek use the repo-level files, so it can't resuse the stack dataset. Which is the key contrbution to this amazing improvment over starcoder,  code quaility filtering, second pretraining or something else?

**Comment by guoday** [comment]
The primary contributions come from many aspects, including data collection, deduplication, filtering, the total number of tokens for pre-training, and the methods of pre-training. The optimization of each process is essential for enhancing the model. We will analyze this further in our later technical reports.

**Comment by feiyuvl** [comment]
Thank you, looking forward to your technical reports

**Comment by wentinghome** [comment]
Hey, thanks for the great work! can you share the script of dependency parsing and repo level dedup?
