### ISSUE TITLE
How to do code completion in Visual studio code?

### ISSUE THREAD

**Issue by vikasd22** [deepseek-ai/DeepSeek-Coder#95]
Hi everyone,
I was wondering how the following completion demo was done in VSCode? I didn't see any information on the readme about it? Maybe I missed it somewhere? 

https://github.com/deepseek-ai/DeepSeek-Coder/blob/main/pictures/completion_demo.gif

**Comment by erfanium** [comment]
@vikasd22 use tabbyml/tabby
